# Generated by Django 4.1.3 on 2022-11-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_update_product_updated_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
